version = 0.1
[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "Readall-dev"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-bp8dyekrfvuu"
s3_prefix = "Readall-dev"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
